name: Deploy Production

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to production
        uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GH_TOKEN_FOR_VERCEL }}
          vercel-org-id: "sztadii"
          vercel-project-id: "crypto-dashboard"
          vercel-args: '--prod'
