name: Quality check

on: [push]

jobs:
  quick-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'

      - name: Dependency instalation
        run: npm install

      - name: Linting
        run: npm run lint

      - name: Unit / integration tests
        run: npm run test-unit

      - name: Checking build
        run: npm run build

      - name: Check bundle size
        run: npx bundlesize

  e2e-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'

      - name: Dependency instalation
        run: npm install

      - name: E2E tests
        run: npm run test-e2e

      - name: Archive cypress artifact on fail
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-artifact
          path: cypress/**
